name: My GitHub Actions Pipeline

on:
  push:
    branches: master 
  
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Change dir
      run: | 
        cd vue-paper-dashboard  
        ls

    - name: Install npm dependencies
      run: nmp install

    - name: Run app
      run: nmp run dev

    - name: Print finish message
      run: echo "Pipeline finished."
  